### ISSUE TITLE
Make rdfstore work with Atom.io

### ISSUE THREAD

**Issue by aldonline** [antoniogarrote/rdfstore-js#103]
There are ( at least ) three things that stand in the way:
* sqlite3 does not play nicely with atom-shell ( See: https://github.com/mapbox/node-sqlite3/issues/357 )
* contextify has similar build issues ( and it is a transitive dependency through `jsonld` ) 
* usage of *unsafe* `eval()` needs to be wrapped using [loophole](https://github.com/atom/loophole)

**Comment by antoniogarrote** [comment]
I have added a small frontend for the store built using electron (old atom-shell)
These are the changes: https://github.com/antoniogarrote/rdfstore-js/commit/94c0917c56a065846178c1c3d7ce16856d329731

To run it, you can just run electron from the 'frontend' directory.

Integration as a chrome library is trivial. I have to try intengrating the library as a node library and fix the issues you mention. It's a really interesting option for people to try the library.

Thanks for the suggestion.

**Comment by appelgriebsch** [comment]
Looks like the new version of jsonld 0.4.x no longer have the dependency to contextify (as it has been moved into node.js already). Maybe an update of the package dependencies might be sufficient to resolve the issue...
