### ISSUE TITLE
Cannot find module '../node_modules/n3/lib/N3Parser'

### ISSUE THREAD

**Issue by Spadon** [antoniogarrote/rdfstore-js#114]
Hello,

I installed rdfstore in my project using `npm install --save rdfstore`; however, `require('rdfstore')` fires the following error:
```
Cannot find module '../node_modules/n3/lib/N3Parser'.
...
at Object.<anonymous> ('('basepath)/node_modules/rdfstore/src/rvn3_parser.js:2:16)
```
The two first lines of rvn3_parser.js are
```
(line 1) //var N3Parser = require('n3').Parser;
(line 2) var N3Parser = require('../node_modules/n3/lib/N3Parser');
```
When I manually uncomment line 1 and comment line 2, it works. Is there an actual way to avoid the relative inclusion of N3Parser without downgrading rdfstore's version? Did I misunderstand something?

Thanks,

Mehdi

**Comment by js-seth-h** [comment]
same here!

In node 5.x, I guess because of node_modules locations is changed, it make trouble.

please fix it.

**Comment by rom1504** [comment]
`require('n3/lib/N3Parser');` should fix it

**Comment by n1try** [comment]
https://github.com/antoniogarrote/rdfstore-js/pull/116

**Comment by antoniogarrote** [comment]
Hi I think this problem should have been fixed in the later versions of the store.
Drop me a line if it is not the case.

Thanks!
