### ISSUE TITLE
FILTER NOT EXISTS throws Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Spadon** [antoniogarrote/rdfstore-js#115]
Hi all,

I am trying to launch a SPARQL query against rdfstore, but the FILTER statement throws the following error:
```
TypeError: Cannot read property 'length' of undefined
    at Object.QueryFilters.runBuiltInCall (node_modules/rdfstore/src/query_filters.js:1238:50)
    at Object.QueryFilters.runFilter (node_modules/rdfstore/src/query_filters.js:309:33)
...
```

My SPARQL query:

```
PREFIX asawoo: <http://liris.cnrs.fr/asawoo/vocab#>
PREFIX asawooFunct: <http://liris.cnrs.fr/asawoo/functionality/>
SELECT DISTINCT ?fun WHERE { 
	FILTER NOT EXISTS {
		<http://liris.cnrs.fr/asawoo#WindowMotor> asawoo:hasCapability ?cap .
	}
	{ 
		?fun asawoo:isComposedOf ?funComposite .
		?funComposite asawoo:isImplementedBy ?cap .

	} UNION { 
		?fun asawoo:isImplementedBy ?cap .

	}
 }
```

The query itself works on Protégé 5.

Please find attached the jsonld ontology loaded before querying.
[modified_functionalities.jsonld.zip](https://github.com/antoniogarrote/rdfstore-js/files/208291/modified_functionalities.jsonld.zip)

Thanks,

Mehdi

**Comment by Spadon** [comment]
The problem is located in query_filters.js, line 1230:

```
var result = queryEngine.executeSelectUnit([ {kind:'*'} ],
            dataset,
            ast,
            env, function(r) {
                result = r;
            });
```

The facts is that executeSelectUnit is asynchronous and expects a callback function. This is why result ends `undefined`

**Comment by kenwenzel** [comment]
Hi,

I already fixed this issue by using promises for query filters:

https://github.com/kenwenzel/rdfstore-js/commit/cec194e1dce94e584bcb74e0c86e26c7bd4f8378

I'll prepare a PR when I have some unit tests...

**Comment by antoniogarrote** [comment]
Hi thanks for the bug report. This was lingering since the rewrite of the library.
It's the only corner case when a filter is not synchronous.

I have added a workaround for this problem in version 0.9.11.

If @kenwenzel has a better solution, I would be more than happy to add it.

Cheers!
