### ISSUE TITLE
Error from sqlite3 dependency

### ISSUE THREAD

**Issue by GeorgesAlkhouri** [antoniogarrote/rdfstore-js#117]
Hello guys,

I installed the rdfstore package (v0.9.8) and wanted to start my application with `npm start`, which kicks of a gulp action and transforms my code with babel.

I just imported the package in my code to see if it works. ( `import rdfstore from 'rdfstore';` )

After the successful transformation, node throws wired error and warning messages at me, which I don't understand. ([error.txt](https://github.com/antoniogarrote/rdfstore-js/files/269298/error.txt)) 
Only that it has something to do with the sqlite3 dependency.

I am using Mac OS X with node in version 5.11.1 (also tried in version 6). 

Thank you very much for your help.

**Comment by k00ni** [comment]
Just an idea: maybe the whitespaces in the filepath causes this?

**Comment by GeorgesAlkhouri** [comment]
No, unfortunately not.

**Comment by GeorgesAlkhouri** [comment]
I solved my problem by telling webpack to not put the sqlite3 dependency into the bundle. Because it contains also native code which node cannot execute. 

I added the following code to my webpack config file:

```
module.exports = {
    ...
    ...
    ...
    externals:{
        sqlite3: 'sqlite3'
    }
}
```
