### ISSUE TITLE
Error in btree.js

### ISSUE THREAD

**Issue by MadsHolten** [antoniogarrote/rdfstore-js#153]
Recently I have started to get the following errors:
```
rdfstore\src\btree.js:324
                    if(that.comparator(key, node.keys[idx].key)===1) {
                                                          ^
TypeError: Cannot read property 'key' of null
```

```
rdfstore\src\btree.js:334
                    idx = node.numberActives -1;
                              ^
TypeError: Cannot read property 'numberActives' of null
```

I have no idea what leads to this error, and I can't seem to find a pattern to when it occurs.

**Comment by fkleedorfer** [comment]
I fixed that in our copy. Will check.

**Comment by fkleedorfer** [comment]
If you want a quick fix, here it is https://github.com/researchstudio-sat/webofneeds/commit/c1ad9240b53bb4ba971ef42e11870280f38758cc#diff-d2647e6139e3a0a971420e20014de71d

**Comment by MadsHolten** [comment]
Thanks! I will try that. Maybe make a pull request on it?

**Comment by fkleedorfer** [comment]
Oh and there already is a PR fixing it https://github.com/antoniogarrote/rdfstore-js/pull/110/files

**Comment by MadsHolten** [comment]
Doesn't seem to solve the problem for me :-/

**Comment by MadsHolten** [comment]
So I think I solved the problem. I was trying to shoot multiple files at the store.load() method at the same time, and it didn't like that. My new strategy is to first concatenate the file content and then load it in store.
