### ISSUE TITLE
IndexedDB Backend

### ISSUE THREAD

**Issue by drobbins** [antoniogarrote/rdfstore-js#25]
rdfstore-js is **great**

An IndexedDB backend would be nice, given the storage limitations associated with LocalStorage (e.g. 5 Mb hard limit in Chrome).

**Comment by antoniogarrote** [comment]
An implementation is in progress for version 1.x

**Comment by elf-pavlik** [comment]
@antoniogarrote you still work on rdfstore-js?
please join other people developing RDF libraries in javascript in http://www.w3.org/community/rdfjs

**Comment by antoniogarrote** [comment]
Version 0.9.3 includes an initial implementation of the IndexedDB backend.

```javascript
Store.new({"persistent": true, "name": "myDB"}, callback);
```

Still needs more tests and improvements.
