### ISSUE TITLE
env is undefined in line 5275 (better error message?)

### ISSUE THREAD

**Issue by lpsBetty** [antoniogarrote/rdfstore-js#44]
i am trying to load an JSON-LD file in the store with

<pre>store.load("application/ld+json", data, function(success, results) {</pre>

and i have included this two js files:
<pre>
  http://code.jquery.com/jquery-1.9.1.min.js
  https://raw.github.com/antoniogarrote/rdfstore-js/master/dist/browser/rdf_store.js
</pre>

but i got the following error: is it possible to get a better error message?

<pre>
rdf_store.js (line 5275)
env is undefined

rdf_store.js (line 5276)
Utils.lexicalFormBaseUri@https://raw.github.com/antoniogarrote/rdfstore-js/master/dist/browser/rdf_store.js:391
Utils.lexicalFormTerm@https://raw.github.com/antoniogarrote/rdfstore-js/master/dist/browser/rdf_store.js:404
jsonld.toTriples/callback@https://raw.github.com/antoniogarrote/rdfstore-js/master/dist/browser/rdf_store.js:2701
jsonld.toTriples@https://raw.github.com/antoniogarrote/rdfstore-js/master/dist/browser/rdf_store.js:2748
JSONLDParser.parser.parse@https://raw.github.com/antoniogarrote/rdfstore-js/master/dist/browser/rdf_store.js:5150
RDFLoader.RDFLoader.prototype.tryToParse@https://raw.github.com/antoniogarrote/rdfstore-js/master/dist/browser/rdf_store.js:5267
Store.Store.prototype.load@https://raw.github.com/antoniogarrote/rdfstore-js/master/dist/browser/rdf_store.js:31581
loadData/<@file:///User
b.Callbacks/c@http://code.jquery.com/jquery-1.9.1.min.js:3
b.Callbacks/p.fireWith@http://code.jquery.com/jquery-1.9.1.min.js:3
k@http://code.jquery.com/jquery-1.9.1.min.js:5
.send/r@http://code.jquery.com/jquery-1.9.1.min.js:5
</pre>

**Comment by antoniogarrote** [comment]
Out of date.
