### ISSUE TITLE
Non proper handling of quoted literals (strings with doublequotes) in toString() & toNT()

### ISSUE THREAD

**Issue by ktk** [antoniogarrote/rdfstore-js#71]
There are some issues with the current serialization of NT in regards to quoted literals handling. Strings containing double quotes (") are not properly serialized and thus cannot be parsed by a parser.

From what I can see @l00mi patched that with his pull request for toString() in #60 

But this looks like Turtle serialization while toNT() should be N-Triples only.

See difference between:

http://www.w3.org/TR/turtle/#turtle-literals

and

http://www.w3.org/TR/n-triples/#sec-literals

I guess this is because a triple has to be on one line in N-Triples, which it is not if I have newlines in the """ part.

**Comment by antoniogarrote** [comment]
solved in #131dfbfda65c9dcbd7c492b4827807e37041036b
