### ISSUE TITLE
Load from turtle file fails

### ISSUE THREAD

**Issue by JWorthington** [antoniogarrote/rdfstore-js#73]
When I run this simple test program:
var fs = require('fs');
var rdfstore = require('rdfstore');

var turtleString = fs.readFileSync(process.argv[2]).toString();

new rdfstore.Store({persistent:true, 
                    engine:'mongodb', 
                    name:'test',
                    overwrite:true,
                    mongoPort:27017 // port where the MongoDB server is running, 27017 by default
                   }, function(store) {
      store.load("text/turtle", turtleString, function(success, results) {
              console.log("load success="+success)
             if (success) {
                  console.log("quads inserted="+results.length);
             }}
            );
})

Using the following turtle file:
<http://example.com/john> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/dc/terms/Agent>.
<http://github.com/JWorthington/Dash> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/dc/terms/Project>.
<http://daa.sh/JohnAgent/works-on/DashProject> 
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement>;
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#subject> <http://daa.sh/JohnAgent>;
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate> <http://daa.sh/works-on>;
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#object> <http://daa.sh/DashProject>.

store.load() reports success==true, but nothing gets loaded. What am I doing wrong?

**Comment by antoniogarrote** [comment]
Should be fixed with the latest version of RV N3 parser.
