### ISSUE TITLE
Current version is not compatible with Nodejs MongoDB driver 1.4.x

### ISSUE THREAD

**Issue by yunjiali** [antoniogarrote/rdfstore-js#74]
In my application, I have installed Nodejs driver for MongoDB 1.4.x. Then I installed the latest version of rdfstore-js (July 2014) and persistent the triples in MongoDB. When I execute a simple sparql query like:

> select ?s ?p ?o where {} LIMIT 10

using store.execute(query, callback), it gives an error:

> Query malformed* Closing connection #0

I am sure the triples are successfully stored and when I used driver version 1.3.x in the same application, there was no problem with the query. Is this an issue with the current version?

**Comment by akuckartz** [comment]
Does any of the forks have a solution for this issue?

**Comment by antoniogarrote** [comment]
Out of date. MongoDB is no longer supported.
