### ISSUE TITLE
npm install rdfstore does not work

### ISSUE THREAD

**Issue by biborno** [antoniogarrote/rdfstore-js#78]
Hi,
I was trying to run the command npm install rdfstore. 
here is the output:

D:\ems\node_modules\rdfstore\node_modules\mongodb\node_modules\kerberos>node "C:
\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node
-gyp\bin\node-gyp.js" rebuild
npm http 304 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/domutils
npm http GET https://registry.npmjs.org/domhandler
npm http GET https://registry.npmjs.org/domelementtype
npm http GET https://registry.npmjs.org/entities
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/bl
npm http 304 https://registry.npmjs.org/caseless
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/stringstream
npm http 304 https://registry.npmjs.org/aws-sign2

> contextify@0.1.9 install D:\ems\node_modules\rdfstore\node_modules\jsdom\node_
modules\contextify
> node-gyp rebuild

D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modules\contextify>node "C:
\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node
-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:101:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modules\contex
tify
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm http 304 https://registry.npmjs.org/entities
npm http GET https://registry.npmjs.org/nan/1.3.0
npm http 304 https://registry.npmjs.org/hawk/1.1.1
npm http 304 https://registry.npmjs.org/domutils
npm ERR! Error: ENOENT, open 'D:\ems\node_modules\rdfstore\node_modules\jsdom\no
de_modules\request\node_modules\mime-types\README.md'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rdfstore"
npm ERR! cwd D:\ems
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modules\reque
st\node_modules\mime-types\README.md
npm ERR! code ENOENT
npm ERR! errno 34
npm http 304 https://registry.npmjs.org/domhandler
npm ERR! Error: ENOENT, open 'D:\ems\node_modules\rdfstore\node_modules\jsdom\no
de_modules\request\node_modules\json-stringify-safe\LICENSE'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rdfstore"
npm ERR! cwd D:\ems
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modules\reque
st\node_modules\json-stringify-safe\LICENSE
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, open 'D:\ems\node_modules\rdfstore\node_modules\jsdom\no
de_modules\request\node_modules\caseless\index.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rdfstore"
npm ERR! cwd D:\ems
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modules\reque
st\node_modules\caseless\index.js
npm ERR! code ENOENT
npm ERR! errno 34
npm http 304 https://registry.npmjs.org/domelementtype
npm ERR! Error: ENOENT, lstat 'D:\ems\node_modules\rdfstore\node_modules\jsdom\n
ode_modules\request\node_modules\forever-agent\LICENSE'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rdfstore"
npm ERR! cwd D:\ems
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modules\reque
st\node_modules\forever-agent\LICENSE
npm ERR! fstream_path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modul
es\request\node_modules\forever-agent\LICENSE
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm WARN optional dep failed, continuing aws-sign2@0.5.0
npm WARN optional dep failed, continuing stringstream@0.0.4
npm WARN optional dep failed, continuing oauth-sign@0.4.0
npm WARN optional dep failed, continuing form-data@0.1.4
npm ERR! Error: ENOENT, lstat 'D:\ems\node_modules\rdfstore\node_modules\jsdom\n
ode_modules\request\node_modules\hawk\LICENSE'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rdfstore"
npm ERR! cwd D:\ems
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modules\reque
st\node_modules\hawk\LICENSE
npm ERR! fstream_path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modul
es\request\node_modules\hawk\LICENSE
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, open 'D:\ems\node_modules\rdfstore\node_modules\jsdom\no
de_modules\request\node_modules\node-uuid\benchmark\bench.gnu'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rdfstore"
npm ERR! cwd D:\ems
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modules\reque
st\node_modules\node-uuid\benchmark\bench.gnu
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, lstat 'D:\ems\node_modules\rdfstore\node_modules\jsdom\n
ode_modules\request\node_modules\tough-cookie\generate-pubsuffix.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rdfstore"
npm ERR! cwd D:\ems
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modules\reque
st\node_modules\tough-cookie\generate-pubsuffix.js
npm ERR! fstream_path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modul
es\request\node_modules\tough-cookie\generate-pubsuffix.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'D:\ems\node_modules\rdfstore\node_modules\jsdom\n
ode_modules\request\node_modules\http-signature\lib\parser.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rdfstore"
npm ERR! cwd D:\ems
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modules\reque
st\node_modules\http-signature\lib\parser.js
npm ERR! fstream_path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modul
es\request\node_modules\http-signature\lib\parser.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/nan/1.3.0
npm ERR! Error: ENOENT, lstat 'D:\ems\node_modules\rdfstore\node_modules\jsdom\n
ode_modules\request\node_modules\qs\lib\stringify.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rdfstore"
npm ERR! cwd D:\ems
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modules\reque
st\node_modules\qs\lib\stringify.js
npm ERR! fstream_path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modul
es\request\node_modules\qs\lib\stringify.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'D:\ems\node_modules\rdfstore\node_modules\jsdom\n
ode_modules\request\node_modules\bl\test\basic-test.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rdfstore"
npm ERR! cwd D:\ems
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modules\reque
st\node_modules\bl\test\basic-test.js
npm ERR! fstream_path D:\ems\node_modules\rdfstore\node_modules\jsdom\node_modul
es\request\node_modules\bl\test\basic-test.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)

> bson@0.2.15 install D:\ems\node_modules\rdfstore\node_modules\mongodb\node_mod
ules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

D:\ems\node_modules\rdfstore\node_modules\mongodb\node_modules\bson>node "C:\Pro
gram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp
\bin\node-gyp.js" rebuild
npm ERR! contextify@0.1.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.9 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rdfstore"
npm ERR! cwd D:\ems
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\ems\npm-debug.log
npm ERR! not ok code 0

D:\ems>

**Comment by antoniogarrote** [comment]
Out of date. Fixed.
