### ISSUE TITLE
Make the graph rdf-interface api available to the store

### ISSUE THREAD

**Issue by meDavid** [antoniogarrote/rdfstore-js#9]
For now, to get a handle to the rdf-interface you need to either query the store or use the graph() or node() methods. These will return a graph object (snapshot) with the rdf-interface api. I would like to have the rdf-interface api available on the whole store, without creating snapshots and using callbacks.

The filter function could use the indexes that are available in the store backend

**Comment by antoniogarrote** [comment]
This is possible through the Store.rdf and Store.rdf.api properties.
