### ISSUE TITLE
Query Plan

### ISSUE THREAD

**Issue by theylooksotired** [antoniogarrote/rdfstore-js#91]
I think that you have a bug in the following line:

node_modules/rdfstore/src/query_plan.js:469
                                  results[j][graphVar] = dataset.named[i].oid;

There's no [i] index... I changed to j just to test and it works

**Comment by antoniogarrote** [comment]
Thanks a lot!

Using named graphs in the environment of the query was not covered in the test suite. The error was still lingering from the the old synchronous code.

I have fixed the problem and added a test for the fuctionality: https://github.com/antoniogarrote/rdfstore-js/commit/78737228f16ea81446de2b0537e6c12ec4e46a59
