### ISSUE TITLE
NotFound exception for index

### ISSUE THREAD

**Issue by johlrogge** [antoniogarrote/rdfstore-js#94]
I tried to use a persistent store in firefox yesterday and I got a not found exception when getting the `literal` index. Could it be that the indexes are not created and it works on local developer stores because they have been created in the past?

It is easy to reproduce, just create a store with `{persitent:true}` and do an insert. I havn't had the time to look into it much yet but I will during the week when time permits. 

Thanks /J

**Comment by johlrogge** [comment]
Some more information

```
NotFoundError: The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened.
http://localhost:8000/hoarders/bower_components/rdfstore/rdfstore.js
Line 23470
```
Here is my examplecode:

```javascript
define(['rdfstore'],
       function(rdfstore){
           new Store({name:'test', overwrite:false, persistent:true}, function(err,store) {
               var query = 'PREFIX foaf: <http://xmlns.com/foaf/0.1/>\
                     PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\
                     PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\
                     PREFIX : <http://example.org/people/>\
                     INSERT DATA {\
                     :alice\
                         rdf:type        foaf:Person ;\
                         foaf:name       "Alice" ;\
                         foaf:mbox       <mailto:alice@work> ;\
                         foaf:knows      :bob \
                         .\
                     :bob\
                         rdf:type        foaf:Person ;\
                         foaf:name       "Bob" ; \
                         foaf:knows      :alice ;\
                         foaf:mbox       <mailto:bob@home> \
                         .\
                     }';
        store.execute(query, function(err, results) {
            store.graph(function(err, graph){
                var results = graph.filter( store.rdf.filters.describes("http://example.org/people/alice") );

                var resultsCount = results.toArray().length;

                var resultsSubject = results.filter(store.rdf.filters.s("http://example.org/people/alice"))
                var resultsObject  = results.filter(store.rdf.filters.o("http://example.org/people/alice"))
                
                console.log(resultsObject);
            });
        });
    });           
});

```

**Comment by antoniogarrote** [comment]
The code looks correct and it's working on my test systems.

Have you used an older version of the store in the same domain?

Latest version includes changes in the indexdb definition and if you try to use it for the same DB it will fail because the schema doesn't match.

If that is the case, the example should work just changing the name of the database from 'test' to some new identifier or removing the indexdb databases from the system through the browser settings.

A way of dealing with changes in the schema for the indices created by the library without breaking applications using the store needs to be implemented.

**Comment by johlrogge** [comment]
Thank you for the quick reply. Fetched the new repository yesterday, rebuilt, changed the name to test2, cleared my cache, reloaded and had the same result in firefox.

Just to make sure I tested the same thing in chrome with the same result.

I got a more elaborate stack trace from chrome though.

```
Uncaught NotFoundError: Failed to execute 'index' on 'IDBObjectStore': The specified index was not found.52.Lexicon.registerLiteral @ rdfstore.js:2347056.QueryEngine.normalizeTerm @ rdfstore.js:24651(anonymous function) @ rdfstore.js:24762(anonymous function) @ rdfstore.js:29894(anonymous function) @ rdfstore.js:2987862.iterate @ rdfstore.js:29856(anonymous function) @ rdfstore.js:29867(anonymous function) @ rdfstore.js:29880(anonymous function) @ rdfstore.js:29897(anonymous function) @ rdfstore.js:2475152.Lexicon.registerUri.request.onsuccess.requestAdd.onsuccess @ rdfstore.js:23337
```
I will not have time to dig deeper tonight but perhaps tomorrow. Do you have a pointer to where the schema is created so I can debug a bit?

**Comment by antoniogarrote** [comment]
I see, not sure of what's going on.
Have you tried using the inspecto in Chrome to check if the indices are created? You should have a 'test2_lexicon' and 'test2_db' indices associated to the domain.

The indices are created in 'src/persistent_lexicon.js' and 'src/persistent_quad_backend.js' in the Lexicon and QuadBackend functions.

In the concatenated file 'dist/rdfstore.js' search for line numbers 22897 for the lexicon and 23433 for the quad backend.

Another test you can do is running the browser tests and see if they are passing. You can just open the file: 'spec/browser/index.html'.

If you can pass me the whole file with your test I will try to debug it.

Sorry for the problems, I'm still working on the persistent version with IndexedDB.

**Comment by johlrogge** [comment]
Thanks. I'll look into it tomorrow and I will also try to make a more shareable testcase if I can't figure out what is wrong on my own.

**Comment by johlrogge** [comment]
I got it to work now. I noticed that my old file was called ```rdfstore.js``` and the new ones were called ```rdf_store.js```. So if I had paid more attention I would have gotten it to work after the last rebuild (I did have to rename the DB again as you suggested though).

Thanks for your help and sorry for not noticing when the problem was actually solved.

**Comment by antoniogarrote** [comment]
No worries!
It's really useful to have other eyes looking at the code.
Cheers.
